import {ReactNode} from "react";
import "@/assets/styles/globals.scss"
import {LayoutMain} from "@/widgets";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <LayoutMain>
            {children}
        </LayoutMain>
        </html>
    )
}
